swagger: '2.0'
info:
  title: MCPCalculatorDemo
  description: Calculate BMI, Calculate sum, and Country facts using MCP SSE server
  version: '1.0'
host: my-mcp-service-btgmhmesdfhsh9ef.eastus-01.azurewebsites.net
basePath: /
schemes:
  - https

definitions:
  QueryResponse:
    type: object
    properties:
      jsonrpc:
        type: string
      id:
        type: string
      method:
        type: string
      params:
        type: object
      result:
        type: object
      error:
        type: object

paths:
  /sse:
    get:
      summary: MCP Server Actions for calculating BMI, sum, and country facts
      operationId: CalculatorDemo_SSE
      tags:
        - Agentic
        - McpSse
      parameters:
        - in: query
          name: sessionId
          type: string
          required: false
      produces:
        - application/json
      responses:
        '200':
          description: Immediate Response
          schema:
            $ref: '#/definitions/QueryResponse'
        '201':
          description: Created and will follow callback

  /country-facts:
    post:
      summary: Get three facts about a country via MCP
      operationId: GetCountryFacts
      tags:
        - Agentic
        - McpSse
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: query
          name: sessionId
          type: string
          required: true
          description: SSE session ID for streaming results
        - in: body
          name: body
          required: true
          description: JSON object containing the country name
          schema:
            type: object
            required:
              - country
            properties:
              country:
                type: string
                description: Name of the country to fetch facts for
      responses:
        '200':
          description: Country facts result
          schema:
            type: object
            properties:
              capital:
                type: string
              region:
                type: string
              population:
                type: integer

securityDefinitions: {}
security: []
