swagger: '2.0'
info:
  title: MCPServerDEmo
  description: Dedicated endpoints for calculate-sum, calculate-bmi & country-facts
  version: '1.0'
host: my-mcp-service-btgmhmesdfhsh9ef.eastus-01.azurewebsites.net    # e.g. my-mcp-service-xyz.eastus-01.azurewebsites.net
basePath: /
schemes:
  - https

paths:
  /sum:
    post:
      summary: Calculate the sum of two numbers
      operationId: calculateSum
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: sessionId
          in: query
          type: string
          required: true
          description: SSE session ID
        - name: body
          in: body
          required: true
          description: Object with numbers to sum
          schema:
            type: object
            properties:
              a:
                type: number
                description: First number
              b:
                type: number
                description: Second number
            required:
              - a
              - b
      responses:
        '200':
          description: Sum result
          schema:
            type: object
            properties:
              sum:
                type: number

  /bmi:
    post:
      summary: Calculate Body Mass Index (BMI)
      operationId: calculateBmi
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: sessionId
          in: query
          type: string
          required: true
          description: SSE session ID
        - name: body
          in: body
          required: true
          description: Object with height and weight
          schema:
            type: object
            properties:
              height:
                type: number
                description: Height in meters
              weight:
                type: number
                description: Weight in kilograms
            required:
              - height
              - weight
      responses:
        '200':
          description: BMI result
          schema:
            type: object
            properties:
              bmi:
                type: number

  /country-facts:
    post:
      summary: Get three facts about a country
      operationId: getCountryFacts
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: sessionId
          in: query
          type: string
          required: true
          description: SSE session ID
        - name: body
          in: body
          required: true
          description: Object with country name
          schema:
            type: object
            properties:
              country:
                type: string
                description: Country to fetch facts for
            required:
              - country
      responses:
        '200':
          description: Country facts result
          schema:
            type: object
            properties:
              capital:
                type: string
              region:
                type: string
              population:
                type: integer

securityDefinitions: {}
security: []
